"""The row module. It names each row. Comparisons live in the judges."""

from tools.gate import drive, hex1rows, hex2rows, m0rows


def all_rows(gate):
    drive.row_prover(gate)
    drive.row_hex_check(gate)
    drive.row_sed(gate)
    drive.row_fixpoint(gate)
    drive.row_exit42(gate)
    drive.row_mode(gate)
    drive.row_formats(gate)
    drive.row_refusals(gate)
    drive.row_syscalls(gate)
    drive.row_disasm(gate)
    drive.row_size(gate)
    drive.row_lint(gate)
    drive.row_fuzz(gate)
    drive.row_faults(gate)
    drive.row_sigxfsz(gate)
    drive.row_capability(gate)
    drive.row_empty_argv(gate)
    drive.row_fd300(gate)
    drive.row_sha(gate)
    drive.row_layout(gate)
    drive.row_outer(gate)
    drive.row_clone(gate)
    drive.row_hostile(gate)
    drive.row_signals(gate)
    drive.row_lock(gate)
    drive.row_ast(gate)
    drive.row_effect(gate)
    hex1rows.row_hex1_parity(gate)
    hex1rows.row_hex1_labels(gate)
    hex1rows.row_hex1_bad(gate)
    hex1rows.row_hex1_refusals(gate)
    hex1rows.row_hex1_self(gate)
    hex1rows.row_hex1_syscalls(gate)
    hex1rows.row_hex1_disasm(gate)
    hex1rows.row_hex1_size(gate)
    hex1rows.row_hex1_lseek(gate)
    hex2rows.row_hex2_parity(gate)
    hex2rows.row_hex2_widths(gate)
    hex2rows.row_hex2_bad(gate)
    hex2rows.row_hex2_self(gate)
    hex2rows.row_hex2_syscalls(gate)
    hex2rows.row_hex2_disasm(gate)
    hex2rows.row_hex2_size(gate)
    hex2rows.row_hex2_lseek(gate)
    m0rows.row_m0_text(gate)
    m0rows.row_m0_refusals(gate)
    m0rows.row_m0_self(gate)
    m0rows.row_m0_syscalls(gate)
    m0rows.row_m0_disasm(gate)
    m0rows.row_m0_size(gate)
    drive.finish(gate)
